# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21a4e2480e4ea7b07c7ce96480a90e2eef5802d6afddfdb9ba4a91ebb39a871dac4bc54f3b7a4023ca0469ca14c50b20daafd3c50d5685d3ebb00b4fc38354ec

test:
  secret_key_base: 9537eef2e583816fcdc3f57b1b4885cc8498667f6cd30008e75f0388d7d06c9fc28b4cb6894b96e632e33d2616a37e045c2cf2fd165902516a71279a260762eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
